# CSV types (txt files)
const GTFS_TYPES = Dict{Symbol, Type}(
    :GTFSID => Union{String, Missing},
    :GTFSEnum => Union{Int64, Missing},
    :GTFSTimezone => Union{String, Missing},
    :GTFSDate => Union{String, Missing},
    :GTFSTime => Union{String, Missing},
    :GTFSLocalTime => Union{String, Missing},
    :GTFSLatitude => Union{Float64, Missing},
    :GTFSLongitude => Union{Float64, Missing},
    :GTFSFloat => Union{Float64, Missing},
    :GTFSInteger => Union{Int64, Missing},
    :GTFSText => Union{String, Missing},
    :GTFSEmail => Union{String, Missing},
    :GTFSPhoneNumber => Union{String, Missing},
    :GTFSURL => Union{String, Missing},
    :GTFSLanguageCode => Union{String, Missing},
    :GTFSCurrencyCode => Union{String, Missing},
    :GTFSCurrencyAmount => Union{String, Missing},
    :GTFSColor => Union{String, Missing},
)
