# This file is auto-generated. Do not edit manually.
# Generated by: generation/generation/validation_types_generator.jl

"""
    ValidationMessage

Represents a specific validation message with context.

# Fields
- `file::String`: Name of the GTFS file where the message occurred
- `field::Union{String, Nothing}`: Name of the field (if applicable)
- `message::String`: Message text
- `severity::Symbol`: Message severity (:error, :warning, or :info)
"""
struct ValidationMessage
    file::String
    field::Union{String, Nothing}
    message::String
    severity::Symbol  # :error, :warning, or :info
end

"""
    ValidationResult

Result of GTFS validation containing errors and warnings.

# Fields
- `is_valid::Bool`: Whether the GTFS feed is valid
- `messages::Vector{ValidationMessage}`: List of validation messages
- `summary::String`: Summary of validation results
"""
struct ValidationResult
    is_valid::Bool
    messages::Vector{ValidationMessage}
    summary::String
end